language: node_js
node_js:
  - "10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
bundler_args: --retry 3
before_install:  
  - npm install -g npm
  - npm install -g codecov
script:
  - npm run build
  - travis_retry npm run test:unit
cache:
  directories:
    - "node_modules"
after_success: 
  - npm run coverage
notifications:
  email: false