export const SET_HIGHLIGHTS = "SET_HIGHLIGHTS";
export const SET_FEED = "SET_FEED";
export const SET_INTEREST = "SET_INTEREST";
export const SET_LATEST_JOURNAL_ARTICLES = "SET_LATEST_JOURNAL_ARTICLES";
export const SET_ERROR = "SET_ERROR";
