export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const SET_DRAWER = 'SET_DRAWER'
export const SET_HOME = 'SET_HOME'
export const SET_ONLINE = 'SET_ONLINE'
export const SET_OFFLINE = 'SET_OFFLINE'
export const RESTORE_MUTATION = 'RESTORE_MUTATION'
export const SET_PARALLAX_IMG = 'SET_PARALLAX_IMG'
export const SET_MOBILE = 'SET_MOBILE'
