export const SET_CME_MODULES_TOTAL = "SET_CME_MODULES_TOTAL";
export const SET_CME_MODULES = "SET_CME_MODULES";
export const SET_CME_MODULE = "SET_CME_MODULE";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const RESET_RESULTS = "RESET_RESULTS";
