export const SET_USER = 'SET_USER'
export const SET_INTERESTS = 'SET_INTERESTS'
export const SET_PREFERENCES = 'SET_PREFERENCES'
export const SET_STATUS = 'SET_STATUS'
export const SET_ERROR = 'SET_ERROR'
export const LOGOUT = 'LOGOUT'
